### ISSUE TITLE
Links not work

### ISSUE THREAD

**Issue by txmodxoops** [xoops-pi/engine#6]
After good installation of alpha 3, all links not work e.g. http://localhost/XoopsEngine/htdocs/system, http://localhost/XoopsEngine/htdocs/root, http://localhost/XoopsEngine/htdocs/admin. The folders system, admin and root not exist in htdocs, This causes errors, 

Not Found

The requested URL /XoopsEngine/htdocs/root was not found on this server.

as the pages are called?

Thanks

**Comment by ghost** [comment]
Is you mod_rewrite works ?

**Comment by txmodxoops** [comment]
Yes this is active

**Comment by yaodong** [comment]
Is the file .htaccess exists in your htdocs?

**Comment by txmodxoops** [comment]
Ok now work, on win xp I have do renamed .htaccess in htaccess.txt Thanks
